spring.application.name=VD2_24110171
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# SQL Server - JDBC truc tiep, KHONG JPA/Hibernate
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webst9;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=chien722006
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Database duoc tao bang file SQL trong folder database, Spring KHONG tu tao bang.
spring.sql.init.mode=never

# UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
